services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7007:7007"
    environment:
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chat-network
    
  postgres:
    image: postgres:16
    container_name: chat-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

volumes:
  postgres_data:
    driver: local

networks:
  chat-network:
    driver: bridge
